services:
    uecode.listener.before_controller:
        class: Uecode\Bundle\CommonBundle\EventListener\ControllerListener
        calls:
            - [ setDispatcher, [ @event_dispatcher ] ]
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]
            - [ setUserService, [ @uecode.user ] ]
            - [ setResponseService, [ @uecode.response ] ]
            - [ setViewService, [ @uecode.view ] ]
        tags:
            - { name: kernel.event_listener, event: kernel.controller, method: preController }
