services:
    uecode.user:
        class: Uecode\Bundle\CommonBundle\Service\UserService
        arguments: [ %uecode.services.user.entity%, %uecode.services.user.id_property% ]
        calls:
            - [ setSecurityContext, [ @security.context ] ]
            - [ setEntityManager, [ @doctrine.orm.entity_manager ] ]
            - [ init ]
    uecode.view:
        class: Uecode\Bundle\CommonBundle\Service\ViewService
        calls:
            - [ init ]
    uecode.response:
        class: Uecode\Bundle\CommonBundle\Service\ResponseService
        calls:
            - [ setDispatcher, [ @event_dispatcher ] ]
            - [ setTemplating, [ @templating ] ]
            - [ setView, [ @uecode.view ] ]
            - [ setKernel, [ @kernel ] ]
            - [ init ]
