services:
    uecode.twig.extension.inspect:
        class: Uecode\Bundle\CommonBundle\Extension\InspectExtension
        tags:
            - { name: 'twig.extension' }
    uecode.twig.extension.file:
        class: Uecode\Bundle\CommonBundle\Extension\FileExtension
        arguments: [ @kernel ]
        tags:
            - { name: 'twig.extension' }
    uecode.twig.extension.string:
        class: Uecode\Bundle\CommonBundle\Extension\StringExtension
        tags:
            - { name: 'twig.extension' }
