services:
    uecode.user:
        class: Uecode\Bundle\CommonBundle\Service\UserService
        arguments: [ "@?security.context" ]
    uecode.view:
        class: Uecode\Bundle\CommonBundle\Service\ViewService
    uecode.response:
        class: Uecode\Bundle\CommonBundle\Service\ResponseService
        calls:
            - [ setDispatcher, [ @event_dispatcher ] ]
            - [ setTemplating, [ @templating ] ]
            - [ setView, [ @uecode.view ] ]
            - [ setKernel, [ @kernel ] ]
